site_name: damage/fcheck 
docs_dir: 'docs'
nav:
  - File manifest tools damage and fcheck: index.md
  - How to use the damage utility: how_to_use_damage.md
  - Building damage as standalone application: building_damage_binary.md
  - API reference for fcheck: api_reference.md
  - Frequently asked questions: faq.md
  - Credits: credits.md

markdown_extensions:
  - smarty
  - toc:
      permalink: True
  - codehilite
  - attr_list

theme: readthedocs
